[package]
name = "retrieval"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
database.workspace = true
domain.workspace = true
rusqlite.workspace = true
unicode-normalization = "0.1.25"

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
