[package]
name = "assistant"
version = "0.4.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
zip = { version = "=2.4.2", default-features = false }

[dev-dependencies]
quick-xml = { version = "=0.39.4", default-features = false }
