"""Inspect real saved AI exports, render every PDF page, and compare exported text."""
from pathlib import Path
import json
import re
import subprocess
import zipfile
import xml.etree.ElementTree as ET
import pypdfium2 as pdfium
from pypdf import PdfReader

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'output/ai-upgrade-exports'
NAMES = ['writing-1', 'writing-2', 'writing-3', 'long-table']
PS = r'''
$ErrorActionPreference='Stop'
$word=New-Object -ComObject Word.Application
$word.Visible=$false
$word.DisplayAlerts=0
try {
 foreach($name in (ConvertFrom-Json $env:LAWYER_QA_NAMES)) {
  $source=[IO.Path]::Combine($env:LAWYER_QA_EXPORTS,$name+'.docx')
  $target=[IO.Path]::Combine($env:LAWYER_QA_EXPORTS,$name+'-word.pdf')
  $doc=$word.Documents.Open($source,$false,$true)
  try { $doc.ExportAsFixedFormat($target,17) } finally { $doc.Close(0) }
 }
} finally { $word.Quit() }
'''

def normalize(text):
    return re.sub(r'\s+', '', text).replace('\u00a0', '')

def main():
    import os
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output-dir', type=Path, default=OUT)
    parser.add_argument('--names', nargs='+', default=NAMES)
    args = parser.parse_args()
    output = args.output_dir.resolve()
    names = args.names
    env = dict(os.environ, LAWYER_QA_EXPORTS=str(output), LAWYER_QA_NAMES=json.dumps(names))
    completed = subprocess.run(['powershell.exe', '-NoProfile', '-NonInteractive', '-Command', PS], env=env, capture_output=True, text=True, timeout=240)
    if completed.returncode:
        raise RuntimeError('Word rendering failed: ' + completed.stderr[-1000:])
    report = {'documents': [], 'word_renderer': 'Microsoft Word COM, invisible, read-only source'}
    ns = {'w': 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'}
    for name in names:
        plain = (output / f'{name}.txt').read_text(encoding='utf8')
        with zipfile.ZipFile(output / f'{name}.docx') as z:
            tree = ET.fromstring(z.read('word/document.xml'))
            docx_text = '\n'.join(''.join(t.text or '' for t in p.findall('.//w:t', ns)) for p in tree.findall('.//w:p', ns))
            body_text = re.sub(r'(?m)^\s*(?:\d+\.\s+|•\s*)', '', plain)
            # OOXML list numbers are generated by Word; numbered headings may instead carry
            # their digits in text runs. Normalize paragraph prefixes on both sides equally.
            docx_body = re.sub(r'(?m)^\s*(?:\d+\.\s+|•\s*)', '', docx_text)
            assert normalize(body_text) == normalize(docx_body), f'{name}: docx_text_differs'
            headings = len(tree.findall('.//w:pStyle', ns))
            tables = len(tree.findall('.//w:tbl', ns))
            lists = len(tree.findall('.//w:numPr', ns))
        assert not re.search(r'^\s*(#{1,6}\s|\|\s*---|```)', plain, re.M), f'{name}: markdown_in_txt'
        row = {'name': name, 'headings': headings, 'tables': tables, 'lists': lists, 'pdfs': []}
        for suffix in ['', '-word']:
            filename = output / f'{name}{suffix}.pdf'
            reader = PdfReader(filename)
            text = '\n'.join(p.extract_text() or '' for p in reader.pages)
            (output / f'{name}{suffix}.extracted.txt').write_text(text, encoding='utf8')
            facts = re.findall(r'(?:\d{4}-\d{2}-\d{2}|\d{4}年\d{1,2}月\d{1,2}日|\d{1,3}(?:,\d{3})+(?:\.\d+)?|\d{4,}(?:\.\d+)?)', plain)
            missing = [f for f in facts if normalize(f) not in normalize(text)]
            assert not missing, (name, suffix, 'missing_facts', missing)
            doc = pdfium.PdfDocument(filename)
            images = output / f'{name}{suffix}-pages'
            images.mkdir(exist_ok=True)
            for i in range(len(doc)):
                page = doc[i]
                page.render(scale=1.2).to_pil().save(images / f'page-{i+1}.png')
                page.close()
            doc.close()
            pdf_row = {'filename': filename.name, 'pages': len(reader.pages), 'facts_checked': len(facts), 'missing_facts': missing}
            if name == 'long-table':
                assert tables == 1 and lists >= 5
                # Header repeats on continuation pages; final prose may occupy its own page.
                table_pages = [p.extract_text() or '' for p in reader.pages if '合成证据' in (p.extract_text() or '')]
                assert all('证据名称' in normalize(p) for p in table_pages), 'table_header_not_repeated'
                assert all(f'合成证据{i}' in normalize(text) for i in range(1,81)), 'table_row_lost'
                pdf_row['table_pages'] = len(table_pages)
                pdf_row['all_80_rows_present'] = True
            row['pdfs'].append(pdf_row)
        report['documents'].append(row)
    (output / 'layout-report.json').write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf8')
    print(json.dumps(report, ensure_ascii=False))

if __name__ == '__main__':
    main()
