#![allow(unsafe_code)]

//! Windows CNG AES-256-GCM primitives for the private vault.
//!
//! Keys are generated by BCryptGenRandom and wrapped separately with DPAPI CurrentUser. All
//! callers must supply canonical AAD that binds workspace, case, object, kind and version.

use crate::{protect_local, unprotect_local};
use std::{
    error::Error,
    fmt,
    sync::atomic::{compiler_fence, Ordering},
};

pub const VAULT_CRYPTO_SUITE: &str = "windows-cng-aes-256-gcm-v1";
pub const VAULT_KEY_WRAP_PROVIDER: &str = "windows-dpapi-current-user-v1";
pub const AES_256_KEY_BYTES: usize = 32;
pub const GCM_NONCE_BYTES: usize = 12;
pub const GCM_TAG_BYTES: usize = 16;
pub const MAX_VAULT_OBJECT_BYTES: usize = 128 * 1024 * 1024;
pub const MAX_VAULT_AAD_BYTES: usize = 64 * 1024;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VaultCryptoError {
    PlatformUnavailable,
    EmptyPlaintext,
    ObjectTooLarge,
    AadTooLarge,
    InvalidKey,
    InvalidSealedObject,
    RandomGenerationFailed,
    KeyWrapFailed,
    KeyUnwrapFailed,
    EncryptFailed,
    AuthenticationFailed,
}

impl VaultCryptoError {
    pub const fn code(self) -> &'static str {
        match self {
            Self::PlatformUnavailable => "vault_crypto_platform_unavailable",
            Self::EmptyPlaintext => "vault_crypto_empty_plaintext",
            Self::ObjectTooLarge => "vault_crypto_object_too_large",
            Self::AadTooLarge => "vault_crypto_aad_too_large",
            Self::InvalidKey => "vault_crypto_invalid_key",
            Self::InvalidSealedObject => "vault_crypto_invalid_sealed_object",
            Self::RandomGenerationFailed => "vault_crypto_random_generation_failed",
            Self::KeyWrapFailed => "vault_crypto_key_wrap_failed",
            Self::KeyUnwrapFailed => "vault_crypto_key_unwrap_failed",
            Self::EncryptFailed => "vault_crypto_encrypt_failed",
            Self::AuthenticationFailed => "vault_crypto_authentication_failed",
        }
    }
}

impl fmt::Display for VaultCryptoError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.code())
    }
}

impl Error for VaultCryptoError {}

pub struct SecretKey32([u8; AES_256_KEY_BYTES]);

impl SecretKey32 {
    pub fn generate() -> Result<Self, VaultCryptoError> {
        let mut bytes = [0_u8; AES_256_KEY_BYTES];
        if let Err(error) = platform::random(&mut bytes) {
            zeroize(&mut bytes);
            return Err(error);
        }
        Ok(Self(bytes))
    }

    pub fn from_bytes(bytes: [u8; AES_256_KEY_BYTES]) -> Self {
        Self(bytes)
    }

    fn as_bytes(&self) -> &[u8; AES_256_KEY_BYTES] {
        &self.0
    }
}

impl fmt::Debug for SecretKey32 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("SecretKey32([REDACTED])")
    }
}

impl Drop for SecretKey32 {
    fn drop(&mut self) {
        zeroize(&mut self.0);
    }
}

#[derive(Clone, PartialEq, Eq)]
pub struct AeadSealedV1 {
    nonce: [u8; GCM_NONCE_BYTES],
    ciphertext: Vec<u8>,
    tag: [u8; GCM_TAG_BYTES],
}

impl AeadSealedV1 {
    pub fn from_parts(
        nonce: &[u8],
        ciphertext: Vec<u8>,
        tag: &[u8],
    ) -> Result<Self, VaultCryptoError> {
        if nonce.len() != GCM_NONCE_BYTES
            || tag.len() != GCM_TAG_BYTES
            || ciphertext.is_empty()
            || ciphertext.len() > MAX_VAULT_OBJECT_BYTES
        {
            return Err(VaultCryptoError::InvalidSealedObject);
        }
        let mut fixed_nonce = [0_u8; GCM_NONCE_BYTES];
        fixed_nonce.copy_from_slice(nonce);
        let mut fixed_tag = [0_u8; GCM_TAG_BYTES];
        fixed_tag.copy_from_slice(tag);
        Ok(Self {
            nonce: fixed_nonce,
            ciphertext,
            tag: fixed_tag,
        })
    }

    pub fn nonce(&self) -> &[u8; GCM_NONCE_BYTES] {
        &self.nonce
    }

    pub fn ciphertext(&self) -> &[u8] {
        &self.ciphertext
    }

    pub fn tag(&self) -> &[u8; GCM_TAG_BYTES] {
        &self.tag
    }
}

impl fmt::Debug for AeadSealedV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AeadSealedV1")
            .field("ciphertext_bytes", &self.ciphertext.len())
            .finish_non_exhaustive()
    }
}

pub(crate) fn fill_random(output: &mut [u8]) -> Result<(), VaultCryptoError> {
    platform::random(output)
}

pub fn wrap_case_key(key: &SecretKey32) -> Result<Vec<u8>, VaultCryptoError> {
    protect_local(key.as_bytes()).map_err(|_| VaultCryptoError::KeyWrapFailed)
}

pub fn unwrap_case_key(wrapped: &[u8]) -> Result<SecretKey32, VaultCryptoError> {
    let mut plaintext = unprotect_local(wrapped).map_err(|_| VaultCryptoError::KeyUnwrapFailed)?;
    if plaintext.len() != AES_256_KEY_BYTES {
        zeroize(&mut plaintext);
        return Err(VaultCryptoError::InvalidKey);
    }
    let mut key = [0_u8; AES_256_KEY_BYTES];
    key.copy_from_slice(&plaintext);
    zeroize(&mut plaintext);
    Ok(SecretKey32(key))
}

pub fn seal(
    key: &SecretKey32,
    plaintext: &[u8],
    aad: &[u8],
) -> Result<AeadSealedV1, VaultCryptoError> {
    validate_lengths(plaintext, aad)?;
    let mut nonce = [0_u8; GCM_NONCE_BYTES];
    platform::random(&mut nonce)?;
    let (ciphertext, tag) = platform::seal(key.as_bytes(), &nonce, plaintext, aad)?;
    AeadSealedV1::from_parts(&nonce, ciphertext, &tag)
}

pub fn open(
    key: &SecretKey32,
    sealed: &AeadSealedV1,
    aad: &[u8],
) -> Result<Vec<u8>, VaultCryptoError> {
    validate_lengths(&sealed.ciphertext, aad)?;
    platform::open(
        key.as_bytes(),
        &sealed.nonce,
        &sealed.ciphertext,
        aad,
        &sealed.tag,
    )
}

fn validate_lengths(content: &[u8], aad: &[u8]) -> Result<(), VaultCryptoError> {
    if content.is_empty() {
        return Err(VaultCryptoError::EmptyPlaintext);
    }
    if content.len() > MAX_VAULT_OBJECT_BYTES {
        return Err(VaultCryptoError::ObjectTooLarge);
    }
    if aad.len() > MAX_VAULT_AAD_BYTES {
        return Err(VaultCryptoError::AadTooLarge);
    }
    Ok(())
}

fn zeroize(bytes: &mut [u8]) {
    for byte in bytes {
        unsafe {
            std::ptr::write_volatile(byte, 0);
        }
    }
    compiler_fence(Ordering::SeqCst);
}

#[cfg(windows)]
mod platform {
    use super::{zeroize, VaultCryptoError, AES_256_KEY_BYTES, GCM_NONCE_BYTES, GCM_TAG_BYTES};
    use std::{ffi::c_void, mem::size_of, ptr};
    use windows_sys::Win32::Security::Cryptography::{
        BCryptCloseAlgorithmProvider, BCryptDecrypt, BCryptDestroyKey, BCryptEncrypt,
        BCryptGenRandom, BCryptGenerateSymmetricKey, BCryptGetProperty,
        BCryptOpenAlgorithmProvider, BCryptSetProperty, BCRYPT_AES_ALGORITHM, BCRYPT_ALG_HANDLE,
        BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO, BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO_VERSION,
        BCRYPT_CHAINING_MODE, BCRYPT_CHAIN_MODE_GCM, BCRYPT_KEY_HANDLE, BCRYPT_OBJECT_LENGTH,
        BCRYPT_USE_SYSTEM_PREFERRED_RNG,
    };

    const GCM_WIDE_BYTES_WITH_NUL: u32 = 32;

    struct AlgorithmHandle(BCRYPT_ALG_HANDLE);

    impl Drop for AlgorithmHandle {
        fn drop(&mut self) {
            if !self.0.is_null() {
                let _ = unsafe { BCryptCloseAlgorithmProvider(self.0, 0) };
                self.0 = ptr::null_mut();
            }
        }
    }

    struct KeyHandle {
        handle: BCRYPT_KEY_HANDLE,
        object: Vec<u8>,
    }

    impl Drop for KeyHandle {
        fn drop(&mut self) {
            if !self.handle.is_null() {
                let _ = unsafe { BCryptDestroyKey(self.handle) };
                self.handle = ptr::null_mut();
            }
            zeroize(&mut self.object);
        }
    }

    pub fn random(output: &mut [u8]) -> Result<(), VaultCryptoError> {
        let length =
            u32::try_from(output.len()).map_err(|_| VaultCryptoError::RandomGenerationFailed)?;
        let status = unsafe {
            BCryptGenRandom(
                ptr::null_mut(),
                output.as_mut_ptr(),
                length,
                BCRYPT_USE_SYSTEM_PREFERRED_RNG,
            )
        };
        if status < 0 {
            return Err(VaultCryptoError::RandomGenerationFailed);
        }
        Ok(())
    }

    pub fn seal(
        key: &[u8; AES_256_KEY_BYTES],
        nonce: &[u8; GCM_NONCE_BYTES],
        plaintext: &[u8],
        aad: &[u8],
    ) -> Result<(Vec<u8>, [u8; GCM_TAG_BYTES]), VaultCryptoError> {
        let algorithm = open_aes_gcm()?;
        let key = generate_key(&algorithm, key)?;
        let mut nonce = *nonce;
        let mut tag = [0_u8; GCM_TAG_BYTES];
        let mut info = auth_info(&mut nonce, aad, &mut tag)?;
        let mut output = vec![0_u8; plaintext.len()];
        let input_len =
            u32::try_from(plaintext.len()).map_err(|_| VaultCryptoError::ObjectTooLarge)?;
        let output_len =
            u32::try_from(output.len()).map_err(|_| VaultCryptoError::ObjectTooLarge)?;
        let mut written = 0_u32;
        let status = unsafe {
            BCryptEncrypt(
                key.handle,
                plaintext.as_ptr(),
                input_len,
                (&mut info as *mut BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO).cast::<c_void>(),
                ptr::null_mut(),
                0,
                output.as_mut_ptr(),
                output_len,
                &mut written,
                0,
            )
        };
        if status < 0 || written != output_len {
            zeroize(&mut output);
            return Err(VaultCryptoError::EncryptFailed);
        }
        Ok((output, tag))
    }

    pub fn open(
        key: &[u8; AES_256_KEY_BYTES],
        nonce: &[u8; GCM_NONCE_BYTES],
        ciphertext: &[u8],
        aad: &[u8],
        tag: &[u8; GCM_TAG_BYTES],
    ) -> Result<Vec<u8>, VaultCryptoError> {
        let algorithm = open_aes_gcm()?;
        let key = generate_key(&algorithm, key)?;
        let mut nonce = *nonce;
        let mut tag = *tag;
        let mut info = auth_info(&mut nonce, aad, &mut tag)?;
        let mut output = vec![0_u8; ciphertext.len()];
        let input_len =
            u32::try_from(ciphertext.len()).map_err(|_| VaultCryptoError::ObjectTooLarge)?;
        let output_len =
            u32::try_from(output.len()).map_err(|_| VaultCryptoError::ObjectTooLarge)?;
        let mut written = 0_u32;
        let status = unsafe {
            BCryptDecrypt(
                key.handle,
                ciphertext.as_ptr(),
                input_len,
                (&mut info as *mut BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO).cast::<c_void>(),
                ptr::null_mut(),
                0,
                output.as_mut_ptr(),
                output_len,
                &mut written,
                0,
            )
        };
        if status < 0 || written != output_len {
            zeroize(&mut output);
            return Err(VaultCryptoError::AuthenticationFailed);
        }
        Ok(output)
    }

    fn open_aes_gcm() -> Result<AlgorithmHandle, VaultCryptoError> {
        let mut handle: BCRYPT_ALG_HANDLE = ptr::null_mut();
        let status = unsafe {
            BCryptOpenAlgorithmProvider(&mut handle, BCRYPT_AES_ALGORITHM, ptr::null(), 0)
        };
        if status < 0 || handle.is_null() {
            return Err(VaultCryptoError::EncryptFailed);
        }
        let algorithm = AlgorithmHandle(handle);
        let status = unsafe {
            BCryptSetProperty(
                algorithm.0,
                BCRYPT_CHAINING_MODE,
                BCRYPT_CHAIN_MODE_GCM.cast::<u8>(),
                GCM_WIDE_BYTES_WITH_NUL,
                0,
            )
        };
        if status < 0 {
            return Err(VaultCryptoError::EncryptFailed);
        }
        Ok(algorithm)
    }

    fn generate_key(
        algorithm: &AlgorithmHandle,
        secret: &[u8; AES_256_KEY_BYTES],
    ) -> Result<KeyHandle, VaultCryptoError> {
        let mut object_length_bytes = [0_u8; size_of::<u32>()];
        let mut returned = 0_u32;
        let status = unsafe {
            BCryptGetProperty(
                algorithm.0,
                BCRYPT_OBJECT_LENGTH,
                object_length_bytes.as_mut_ptr(),
                u32::try_from(object_length_bytes.len())
                    .map_err(|_| VaultCryptoError::InvalidKey)?,
                &mut returned,
                0,
            )
        };
        if status < 0 || returned != size_of::<u32>() as u32 {
            return Err(VaultCryptoError::InvalidKey);
        }
        let object_length = u32::from_ne_bytes(object_length_bytes);
        if object_length == 0 {
            return Err(VaultCryptoError::InvalidKey);
        }
        let mut object =
            vec![0_u8; usize::try_from(object_length).map_err(|_| VaultCryptoError::InvalidKey)?];
        let mut handle: BCRYPT_KEY_HANDLE = ptr::null_mut();
        let status = unsafe {
            BCryptGenerateSymmetricKey(
                algorithm.0,
                &mut handle,
                object.as_mut_ptr(),
                object_length,
                secret.as_ptr(),
                AES_256_KEY_BYTES as u32,
                0,
            )
        };
        if status < 0 || handle.is_null() {
            zeroize(&mut object);
            return Err(VaultCryptoError::InvalidKey);
        }
        Ok(KeyHandle { handle, object })
    }

    fn auth_info(
        nonce: &mut [u8; GCM_NONCE_BYTES],
        aad: &[u8],
        tag: &mut [u8; GCM_TAG_BYTES],
    ) -> Result<BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO, VaultCryptoError> {
        let cb_size = u32::try_from(size_of::<BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO>())
            .map_err(|_| VaultCryptoError::InvalidSealedObject)?;
        let cb_aad = u32::try_from(aad.len()).map_err(|_| VaultCryptoError::AadTooLarge)?;
        Ok(BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO {
            cbSize: cb_size,
            dwInfoVersion: BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO_VERSION,
            pbNonce: nonce.as_mut_ptr(),
            cbNonce: GCM_NONCE_BYTES as u32,
            pbAuthData: if aad.is_empty() {
                ptr::null_mut()
            } else {
                aad.as_ptr().cast_mut()
            },
            cbAuthData: cb_aad,
            pbTag: tag.as_mut_ptr(),
            cbTag: GCM_TAG_BYTES as u32,
            pbMacContext: ptr::null_mut(),
            cbMacContext: 0,
            cbAAD: 0,
            cbData: 0,
            dwFlags: 0,
        })
    }
}

#[cfg(not(windows))]
mod platform {
    use super::{VaultCryptoError, AES_256_KEY_BYTES, GCM_NONCE_BYTES, GCM_TAG_BYTES};

    pub fn random(_output: &mut [u8]) -> Result<(), VaultCryptoError> {
        Err(VaultCryptoError::PlatformUnavailable)
    }

    pub fn seal(
        _key: &[u8; AES_256_KEY_BYTES],
        _nonce: &[u8; GCM_NONCE_BYTES],
        _plaintext: &[u8],
        _aad: &[u8],
    ) -> Result<(Vec<u8>, [u8; GCM_TAG_BYTES]), VaultCryptoError> {
        Err(VaultCryptoError::PlatformUnavailable)
    }

    pub fn open(
        _key: &[u8; AES_256_KEY_BYTES],
        _nonce: &[u8; GCM_NONCE_BYTES],
        _ciphertext: &[u8],
        _aad: &[u8],
        _tag: &[u8; GCM_TAG_BYTES],
    ) -> Result<Vec<u8>, VaultCryptoError> {
        Err(VaultCryptoError::PlatformUnavailable)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    #[test]
    fn invalid_lengths_fail_before_platform_calls() {
        let key = SecretKey32::from_bytes([7_u8; AES_256_KEY_BYTES]);
        assert_eq!(
            seal(&key, b"", b"aad"),
            Err(VaultCryptoError::EmptyPlaintext)
        );
        assert!(AeadSealedV1::from_parts(&[0; 11], vec![1], &[0; 16]).is_err());
        assert!(AeadSealedV1::from_parts(&[0; 12], vec![1], &[0; 15]).is_err());
    }

    #[cfg(windows)]
    #[test]
    fn aes_gcm_round_trip_and_dpapi_key_wrap() {
        let key = SecretKey32::generate().expect("generate key");
        let wrapped = wrap_case_key(&key).expect("wrap key");
        let restored = unwrap_case_key(&wrapped).expect("unwrap key");
        let plaintext = b"CASE_RAW_CANARY_SYNTHETIC_ONLY";
        let aad = b"vault-object-v1\0ws_a\0case_a\0obj_a\0source_material\x0001";
        let sealed = seal(&restored, plaintext, aad).expect("seal");
        assert_ne!(sealed.ciphertext(), plaintext);
        assert_eq!(open(&restored, &sealed, aad).expect("open"), plaintext);
        assert!(!format!("{restored:?}").contains("CASE_RAW"));
    }

    #[cfg(windows)]
    #[test]
    fn tampering_and_cross_object_aad_swaps_fail_closed() {
        let key = SecretKey32::generate().expect("generate key");
        let aad = b"vault-object-v1\0case_1\0obj_1\x0001";
        let sealed = seal(&key, b"synthetic private payload", aad).expect("seal");
        assert_eq!(
            open(&key, &sealed, b"vault-object-v1\0case_2\0obj_1\x0001"),
            Err(VaultCryptoError::AuthenticationFailed)
        );

        let mut ciphertext = sealed.ciphertext().to_vec();
        ciphertext[0] ^= 0x80;
        let tampered =
            AeadSealedV1::from_parts(sealed.nonce(), ciphertext, sealed.tag()).expect("parts");
        assert_eq!(
            open(&key, &tampered, aad),
            Err(VaultCryptoError::AuthenticationFailed)
        );

        let mut tag = *sealed.tag();
        tag[0] ^= 0x01;
        let tampered = AeadSealedV1::from_parts(sealed.nonce(), sealed.ciphertext().to_vec(), &tag)
            .expect("parts");
        assert_eq!(
            open(&key, &tampered, aad),
            Err(VaultCryptoError::AuthenticationFailed)
        );
    }

    #[cfg(windows)]
    #[test]
    fn generated_nonces_do_not_repeat_in_sample() {
        let key = SecretKey32::generate().expect("generate key");
        let mut nonces = BTreeSet::new();
        for counter in 0_u32..128 {
            let sealed = seal(&key, &counter.to_le_bytes(), b"nonce-test").expect("seal");
            assert!(nonces.insert(*sealed.nonce()));
        }
    }
}
